name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:  # Missing 'jobs:' keyword
  build_androidApk:
    name: Build Flutter App (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk --debug
      - uses: ncipollo/release-action@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Only create releases on main push
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
